version: '3.8'

services:
  dev-db:
    image: postgres:14-alpine
    volumes:
      - rtech_dev_db:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    restart: always

volumes:
  rtech_dev_db:
